baseURL = "https://emersion.fr/"
languageCode = "en-us"
title = "emersion"
theme = "shimong"
pygmentsCodeFences = true
paginate = 100

[permalinks]
	blog = "/blog/:year/:slug/"

[taxonomies]
	tag = "tags"

[outputs]
	home = ["HTML", "RSS"]
	section = ["HTML", "RSS"]

[outputFormats.RSS]
	mediatype = "application/xml"
	baseName = "rss"
